# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantapp', '0004_auto_20170408_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
